server:
  port: 8080

datasource:
  username: root
  password: 12341234
  url: jdbc:mysql://localhost:3306/superCodingProject1st
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key-source : "super-coding"
  token-valid-time : 3600000

logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# spring data jpa 설정
jpa:
  open-in-view: false
  properties:
    dialect: org.hibernate.dialect.MySQLDialect